apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-v2
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: echo-v2
                port:
                  number: 6060

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
      tier: app
      version: v2
  template:
    metadata:
      labels:
        app: echo
        tier: app
        version: v2
    spec:
      containers:
        - name: echo
          image: node-router-test:v0.1.0
          livenessProbe:
            httpGet:
              path: /
              port: 6060

---
apiVersion: v1
kind: Service
metadata:
  name: echo-v2
spec:
  ports:
    - port: 6060
      protocol: TCP
  selector:
    app: echo
    tier: app
    version: v2
